"""Added password column in testing table

Revision ID: 62c307ad5976
Revises: 8d546cee0880
Create Date: 2024-11-13 09:47:24.730496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c307ad5976'
down_revision: Union[str, None] = '8d546cee0880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testing', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testing', 'password')
    # ### end Alembic commands ###
